package com.leadtone.mas.bizplug.calendar.bean;

public class MbnPeriodcTaskSms {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task_sms.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task_sms.task_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Long taskId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task_sms.title
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task_sms.content
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task_sms.tos
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private String tos;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task_sms.id
     *
     * @return the value of mbn_periodc_task_sms.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task_sms.id
     *
     * @param id the value for mbn_periodc_task_sms.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task_sms.task_id
     *
     * @return the value of mbn_periodc_task_sms.task_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task_sms.task_id
     *
     * @param taskId the value for mbn_periodc_task_sms.task_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task_sms.title
     *
     * @return the value of mbn_periodc_task_sms.title
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task_sms.title
     *
     * @param title the value for mbn_periodc_task_sms.title
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task_sms.content
     *
     * @return the value of mbn_periodc_task_sms.content
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task_sms.content
     *
     * @param content the value for mbn_periodc_task_sms.content
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task_sms.tos
     *
     * @return the value of mbn_periodc_task_sms.tos
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public String getTos() {
        return tos;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task_sms.tos
     *
     * @param tos the value for mbn_periodc_task_sms.tos
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setTos(String tos) {
        this.tos = tos;
    }
}