package com.leadtone.mas.bizplug.calendar.bean;

import java.util.Date;

public class MbnPeriodcTask {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.merchant_pin
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Long merchantPin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.operation_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer operationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.awoke_mode
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer awokeMode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.number
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer number;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.awake_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Date awakeTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.begin_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Date beginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.end_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.awoke_rate
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer awokeRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.expire_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer expireTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.div_day
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer divDay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.div_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer divWeek;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.div_day_of_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer divDayOfWeek;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.div_month
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer divMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.times
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer times;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.status
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.calendar_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer calendarType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.last_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Date lastTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.task_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Integer taskType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_periodc_task.creater
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private Long creater;
    
    /**
     * 已发次数，默认为1
     */
    private Integer sendTimes;
    

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.id
     *
     * @return the value of mbn_periodc_task.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.id
     *
     * @param id the value for mbn_periodc_task.id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.merchant_pin
     *
     * @return the value of mbn_periodc_task.merchant_pin
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Long getMerchantPin() {
        return merchantPin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.merchant_pin
     *
     * @param merchantPin the value for mbn_periodc_task.merchant_pin
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setMerchantPin(Long merchantPin) {
        this.merchantPin = merchantPin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.operation_id
     *
     * @return the value of mbn_periodc_task.operation_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.operation_id
     *
     * @param operationId the value for mbn_periodc_task.operation_id
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.awoke_mode
     *
     * @return the value of mbn_periodc_task.awoke_mode
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getAwokeMode() {
        return awokeMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.awoke_mode
     *
     * @param awokeMode the value for mbn_periodc_task.awoke_mode
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setAwokeMode(Integer awokeMode) {
        this.awokeMode = awokeMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.number
     *
     * @return the value of mbn_periodc_task.number
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.number
     *
     * @param number the value for mbn_periodc_task.number
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.awake_time
     *
     * @return the value of mbn_periodc_task.awake_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Date getAwakeTime() {
        return awakeTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.awake_time
     *
     * @param awakeTime the value for mbn_periodc_task.awake_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setAwakeTime(Date awakeTime) {
        this.awakeTime = awakeTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.begin_time
     *
     * @return the value of mbn_periodc_task.begin_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.begin_time
     *
     * @param beginTime the value for mbn_periodc_task.begin_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.end_time
     *
     * @return the value of mbn_periodc_task.end_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.end_time
     *
     * @param endTime the value for mbn_periodc_task.end_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.awoke_rate
     *
     * @return the value of mbn_periodc_task.awoke_rate
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getAwokeRate() {
        return awokeRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.awoke_rate
     *
     * @param awokeRate the value for mbn_periodc_task.awoke_rate
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setAwokeRate(Integer awokeRate) {
        this.awokeRate = awokeRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.expire_time
     *
     * @return the value of mbn_periodc_task.expire_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.expire_time
     *
     * @param expireTime the value for mbn_periodc_task.expire_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.div_day
     *
     * @return the value of mbn_periodc_task.div_day
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getDivDay() {
        return divDay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.div_day
     *
     * @param divDay the value for mbn_periodc_task.div_day
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setDivDay(Integer divDay) {
        this.divDay = divDay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.div_week
     *
     * @return the value of mbn_periodc_task.div_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getDivWeek() {
        return divWeek;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.div_week
     *
     * @param divWeek the value for mbn_periodc_task.div_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setDivWeek(Integer divWeek) {
        this.divWeek = divWeek;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.div_day_of_week
     *
     * @return the value of mbn_periodc_task.div_day_of_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getDivDayOfWeek() {
        return divDayOfWeek;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.div_day_of_week
     *
     * @param divDayOfWeek the value for mbn_periodc_task.div_day_of_week
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setDivDayOfWeek(Integer divDayOfWeek) {
        this.divDayOfWeek = divDayOfWeek;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.div_month
     *
     * @return the value of mbn_periodc_task.div_month
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getDivMonth() {
        return divMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.div_month
     *
     * @param divMonth the value for mbn_periodc_task.div_month
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setDivMonth(Integer divMonth) {
        this.divMonth = divMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.times
     *
     * @return the value of mbn_periodc_task.times
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.times
     *
     * @param times the value for mbn_periodc_task.times
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.status
     *
     * @return the value of mbn_periodc_task.status
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.status
     *
     * @param status the value for mbn_periodc_task.status
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.calendar_type
     *
     * @return the value of mbn_periodc_task.calendar_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getCalendarType() {
        return calendarType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.calendar_type
     *
     * @param calendarType the value for mbn_periodc_task.calendar_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setCalendarType(Integer calendarType) {
        this.calendarType = calendarType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.last_time
     *
     * @return the value of mbn_periodc_task.last_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.last_time
     *
     * @param lastTime the value for mbn_periodc_task.last_time
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.task_type
     *
     * @return the value of mbn_periodc_task.task_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.task_type
     *
     * @param taskType the value for mbn_periodc_task.task_type
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_periodc_task.creater
     *
     * @return the value of mbn_periodc_task.creater
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_periodc_task.creater
     *
     * @param creater the value for mbn_periodc_task.creater
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

	public Integer getSendTimes() {
		return sendTimes;
	}

	public void setSendTimes(Integer sendTimes) {
		this.sendTimes = sendTimes;
	}
    
    
}