package com.leadtone.mas.bizplug.calendar.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MbnSmsDuanxinriliExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public MbnSmsDuanxinriliExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    protected MbnSmsDuanxinriliExample(MbnSmsDuanxinriliExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andMerchantPinIsNull() {
            addCriterion("merchant_pin is null");
            return this;
        }

        public Criteria andMerchantPinIsNotNull() {
            addCriterion("merchant_pin is not null");
            return this;
        }

        public Criteria andMerchantPinEqualTo(Long value) {
            addCriterion("merchant_pin =", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinNotEqualTo(Long value) {
            addCriterion("merchant_pin <>", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinGreaterThan(Long value) {
            addCriterion("merchant_pin >", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_pin >=", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinLessThan(Long value) {
            addCriterion("merchant_pin <", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinLessThanOrEqualTo(Long value) {
            addCriterion("merchant_pin <=", value, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinIn(List values) {
            addCriterion("merchant_pin in", values, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinNotIn(List values) {
            addCriterion("merchant_pin not in", values, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinBetween(Long value1, Long value2) {
            addCriterion("merchant_pin between", value1, value2, "merchantPin");
            return this;
        }

        public Criteria andMerchantPinNotBetween(Long value1, Long value2) {
            addCriterion("merchant_pin not between", value1, value2, "merchantPin");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("content in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("content not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return this;
        }

        public Criteria andRemindwayIsNull() {
            addCriterion("remindWay is null");
            return this;
        }

        public Criteria andRemindwayIsNotNull() {
            addCriterion("remindWay is not null");
            return this;
        }

        public Criteria andRemindwayEqualTo(Integer value) {
            addCriterion("remindWay =", value, "remindway");
            return this;
        }

        public Criteria andRemindwayNotEqualTo(Integer value) {
            addCriterion("remindWay <>", value, "remindway");
            return this;
        }

        public Criteria andRemindwayGreaterThan(Integer value) {
            addCriterion("remindWay >", value, "remindway");
            return this;
        }

        public Criteria andRemindwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("remindWay >=", value, "remindway");
            return this;
        }

        public Criteria andRemindwayLessThan(Integer value) {
            addCriterion("remindWay <", value, "remindway");
            return this;
        }

        public Criteria andRemindwayLessThanOrEqualTo(Integer value) {
            addCriterion("remindWay <=", value, "remindway");
            return this;
        }

        public Criteria andRemindwayIn(List values) {
            addCriterion("remindWay in", values, "remindway");
            return this;
        }

        public Criteria andRemindwayNotIn(List values) {
            addCriterion("remindWay not in", values, "remindway");
            return this;
        }

        public Criteria andRemindwayBetween(Integer value1, Integer value2) {
            addCriterion("remindWay between", value1, value2, "remindway");
            return this;
        }

        public Criteria andRemindwayNotBetween(Integer value1, Integer value2) {
            addCriterion("remindWay not between", value1, value2, "remindway");
            return this;
        }

        public Criteria andCycletypeIsNull() {
            addCriterion("cycleType is null");
            return this;
        }

        public Criteria andCycletypeIsNotNull() {
            addCriterion("cycleType is not null");
            return this;
        }

        public Criteria andCycletypeEqualTo(Integer value) {
            addCriterion("cycleType =", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeNotEqualTo(Integer value) {
            addCriterion("cycleType <>", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeGreaterThan(Integer value) {
            addCriterion("cycleType >", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("cycleType >=", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeLessThan(Integer value) {
            addCriterion("cycleType <", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeLessThanOrEqualTo(Integer value) {
            addCriterion("cycleType <=", value, "cycletype");
            return this;
        }

        public Criteria andCycletypeIn(List values) {
            addCriterion("cycleType in", values, "cycletype");
            return this;
        }

        public Criteria andCycletypeNotIn(List values) {
            addCriterion("cycleType not in", values, "cycletype");
            return this;
        }

        public Criteria andCycletypeBetween(Integer value1, Integer value2) {
            addCriterion("cycleType between", value1, value2, "cycletype");
            return this;
        }

        public Criteria andCycletypeNotBetween(Integer value1, Integer value2) {
            addCriterion("cycleType not between", value1, value2, "cycletype");
            return this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return this;
        }

        public Criteria andNumberIn(List values) {
            addCriterion("number in", values, "number");
            return this;
        }

        public Criteria andNumberNotIn(List values) {
            addCriterion("number not in", values, "number");
            return this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return this;
        }

        public Criteria andRemindhourIsNull() {
            addCriterion("remindHour is null");
            return this;
        }

        public Criteria andRemindhourIsNotNull() {
            addCriterion("remindHour is not null");
            return this;
        }

        public Criteria andRemindhourEqualTo(Integer value) {
            addCriterion("remindHour =", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourNotEqualTo(Integer value) {
            addCriterion("remindHour <>", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourGreaterThan(Integer value) {
            addCriterion("remindHour >", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourGreaterThanOrEqualTo(Integer value) {
            addCriterion("remindHour >=", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourLessThan(Integer value) {
            addCriterion("remindHour <", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourLessThanOrEqualTo(Integer value) {
            addCriterion("remindHour <=", value, "remindhour");
            return this;
        }

        public Criteria andRemindhourIn(List values) {
            addCriterion("remindHour in", values, "remindhour");
            return this;
        }

        public Criteria andRemindhourNotIn(List values) {
            addCriterion("remindHour not in", values, "remindhour");
            return this;
        }

        public Criteria andRemindhourBetween(Integer value1, Integer value2) {
            addCriterion("remindHour between", value1, value2, "remindhour");
            return this;
        }

        public Criteria andRemindhourNotBetween(Integer value1, Integer value2) {
            addCriterion("remindHour not between", value1, value2, "remindhour");
            return this;
        }

        public Criteria andRemindminutesIsNull() {
            addCriterion("remindMinutes is null");
            return this;
        }

        public Criteria andRemindminutesIsNotNull() {
            addCriterion("remindMinutes is not null");
            return this;
        }

        public Criteria andRemindminutesEqualTo(Integer value) {
            addCriterion("remindMinutes =", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesNotEqualTo(Integer value) {
            addCriterion("remindMinutes <>", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesGreaterThan(Integer value) {
            addCriterion("remindMinutes >", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesGreaterThanOrEqualTo(Integer value) {
            addCriterion("remindMinutes >=", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesLessThan(Integer value) {
            addCriterion("remindMinutes <", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesLessThanOrEqualTo(Integer value) {
            addCriterion("remindMinutes <=", value, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesIn(List values) {
            addCriterion("remindMinutes in", values, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesNotIn(List values) {
            addCriterion("remindMinutes not in", values, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesBetween(Integer value1, Integer value2) {
            addCriterion("remindMinutes between", value1, value2, "remindminutes");
            return this;
        }

        public Criteria andRemindminutesNotBetween(Integer value1, Integer value2) {
            addCriterion("remindMinutes not between", value1, value2, "remindminutes");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return this;
        }

        public Criteria andCreateByEqualTo(Long value) {
            addCriterion("create_by =", value, "createBy");
            return this;
        }

        public Criteria andCreateByNotEqualTo(Long value) {
            addCriterion("create_by <>", value, "createBy");
            return this;
        }

        public Criteria andCreateByGreaterThan(Long value) {
            addCriterion("create_by >", value, "createBy");
            return this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
            addCriterion("create_by >=", value, "createBy");
            return this;
        }

        public Criteria andCreateByLessThan(Long value) {
            addCriterion("create_by <", value, "createBy");
            return this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Long value) {
            addCriterion("create_by <=", value, "createBy");
            return this;
        }

        public Criteria andCreateByIn(List values) {
            addCriterion("create_by in", values, "createBy");
            return this;
        }

        public Criteria andCreateByNotIn(List values) {
            addCriterion("create_by not in", values, "createBy");
            return this;
        }

        public Criteria andCreateByBetween(Long value1, Long value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return this;
        }

        public Criteria andCreateByNotBetween(Long value1, Long value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return this;
        }

        public Criteria andRemindtimeIsNull() {
            addCriterion("remindTime is null");
            return this;
        }

        public Criteria andRemindtimeIsNotNull() {
            addCriterion("remindTime is not null");
            return this;
        }

        public Criteria andRemindtimeEqualTo(Date value) {
            addCriterion("remindTime =", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeNotEqualTo(Date value) {
            addCriterion("remindTime <>", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeGreaterThan(Date value) {
            addCriterion("remindTime >", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("remindTime >=", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeLessThan(Date value) {
            addCriterion("remindTime <", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeLessThanOrEqualTo(Date value) {
            addCriterion("remindTime <=", value, "remindtime");
            return this;
        }

        public Criteria andRemindtimeIn(List values) {
            addCriterion("remindTime in", values, "remindtime");
            return this;
        }

        public Criteria andRemindtimeNotIn(List values) {
            addCriterion("remindTime not in", values, "remindtime");
            return this;
        }

        public Criteria andRemindtimeBetween(Date value1, Date value2) {
            addCriterion("remindTime between", value1, value2, "remindtime");
            return this;
        }

        public Criteria andRemindtimeNotBetween(Date value1, Date value2) {
            addCriterion("remindTime not between", value1, value2, "remindtime");
            return this;
        }
    }
}