package com.leadtone.mas.bizplug.calendar.bean;

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;
import org.apache.struts2.json.annotations.JSONFieldBridge;
import org.apache.struts2.json.bridge.StringBridge;

public class MbnSmsDuanxinrili {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.id
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.merchant_pin
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Long merchantPin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.title
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.content
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.remindWay
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer remindway;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.cycleType
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer cycletype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.number
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer number;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.remindHour
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer remindhour;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.remindMinutes
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer remindminutes;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.type
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.create_time
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.create_by
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Long createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.remindTime
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private Date remindtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mbn_sms_duanxinrili.tos
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    private String tos;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.id
     *
     * @return the value of mbn_sms_duanxinrili.id
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    @JSONFieldBridge(impl = StringBridge.class)
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.id
     *
     * @param id the value for mbn_sms_duanxinrili.id
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.merchant_pin
     *
     * @return the value of mbn_sms_duanxinrili.merchant_pin
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Long getMerchantPin() {
        return merchantPin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.merchant_pin
     *
     * @param merchantPin the value for mbn_sms_duanxinrili.merchant_pin
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setMerchantPin(Long merchantPin) {
        this.merchantPin = merchantPin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.title
     *
     * @return the value of mbn_sms_duanxinrili.title
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.title
     *
     * @param title the value for mbn_sms_duanxinrili.title
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.content
     *
     * @return the value of mbn_sms_duanxinrili.content
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.content
     *
     * @param content the value for mbn_sms_duanxinrili.content
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.remindWay
     *
     * @return the value of mbn_sms_duanxinrili.remindWay
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getRemindway() {
        return remindway;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.remindWay
     *
     * @param remindway the value for mbn_sms_duanxinrili.remindWay
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setRemindway(Integer remindway) {
        this.remindway = remindway;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.cycleType
     *
     * @return the value of mbn_sms_duanxinrili.cycleType
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getCycletype() {
        return cycletype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.cycleType
     *
     * @param cycletype the value for mbn_sms_duanxinrili.cycleType
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setCycletype(Integer cycletype) {
        this.cycletype = cycletype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.number
     *
     * @return the value of mbn_sms_duanxinrili.number
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.number
     *
     * @param number the value for mbn_sms_duanxinrili.number
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.remindHour
     *
     * @return the value of mbn_sms_duanxinrili.remindHour
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getRemindhour() {
        return remindhour;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.remindHour
     *
     * @param remindhour the value for mbn_sms_duanxinrili.remindHour
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setRemindhour(Integer remindhour) {
        this.remindhour = remindhour;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.remindMinutes
     *
     * @return the value of mbn_sms_duanxinrili.remindMinutes
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getRemindminutes() {
        return remindminutes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.remindMinutes
     *
     * @param remindminutes the value for mbn_sms_duanxinrili.remindMinutes
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setRemindminutes(Integer remindminutes) {
        this.remindminutes = remindminutes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.type
     *
     * @return the value of mbn_sms_duanxinrili.type
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.type
     *
     * @param type the value for mbn_sms_duanxinrili.type
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.create_time
     *
     * @return the value of mbn_sms_duanxinrili.create_time
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    @JSON(format="yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.create_time
     *
     * @param createTime the value for mbn_sms_duanxinrili.create_time
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.create_by
     *
     * @return the value of mbn_sms_duanxinrili.create_by
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    @JSONFieldBridge(impl = StringBridge.class)
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.create_by
     *
     * @param createBy the value for mbn_sms_duanxinrili.create_by
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.remindTime
     *
     * @return the value of mbn_sms_duanxinrili.remindTime
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    @JSON(format="yyyy-MM-dd HH:mm:ss")
    public Date getRemindtime() {
        return remindtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.remindTime
     *
     * @param remindtime the value for mbn_sms_duanxinrili.remindTime
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setRemindtime(Date remindtime) {
        this.remindtime = remindtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mbn_sms_duanxinrili.tos
     *
     * @return the value of mbn_sms_duanxinrili.tos
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public String getTos() {
        return tos;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mbn_sms_duanxinrili.tos
     *
     * @param tos the value for mbn_sms_duanxinrili.tos
     *
     * @abatorgenerated Tue Jan 29 18:28:52 CST 2013
     */
    public void setTos(String tos) {
        this.tos = tos;
    }
}