package com.leadtone.mas.bizplug.calendar.dao;

import com.leadtone.mas.bizplug.calendar.bean.MbnPeriodcTaskSms;
import com.leadtone.mas.bizplug.calendar.bean.MbnPeriodcTaskSmsExample;
import com.leadtone.mas.bizplug.dao.BaseDao;
import java.sql.SQLException;
import java.util.List;

import org.springframework.stereotype.Component;

@Component("smsMbnPeriodcTaskSmsDAO")
public class MbnPeriodcTaskSmsDAOImpl  extends BaseDao implements MbnPeriodcTaskSmsDAO {
   

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void insert(MbnPeriodcTaskSms record) throws SQLException {
    	this.getSqlMapClientTemplate().insert("mbn_periodc_task_sms.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(MbnPeriodcTaskSms record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(MbnPeriodcTaskSms record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByPrimaryKeySelective(MbnPeriodcTaskSms record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public List selectByExampleWithoutBLOBs(MbnPeriodcTaskSmsExample example) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_periodc_task_sms.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public List selectByExampleWithBLOBs(MbnPeriodcTaskSmsExample example) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_periodc_task_sms.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public MbnPeriodcTaskSms selectByPrimaryKey(Long id) throws SQLException {
        MbnPeriodcTaskSms key = new MbnPeriodcTaskSms();
        key.setId(id);
        MbnPeriodcTaskSms record = (MbnPeriodcTaskSms) this.getSqlMapClientTemplate().queryForObject("mbn_periodc_task_sms.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int deleteByExample(MbnPeriodcTaskSmsExample example) throws SQLException {
        int rows = this.getSqlMapClientTemplate().delete("mbn_periodc_task_sms.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        MbnPeriodcTaskSms key = new MbnPeriodcTaskSms();
        key.setId(id);
        int rows = this.getSqlMapClientTemplate().delete("mbn_periodc_task_sms.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int countByExample(MbnPeriodcTaskSmsExample example) throws SQLException {
        Integer count = (Integer)  this.getSqlMapClientTemplate().queryForObject("mbn_periodc_task_sms.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByExampleSelective(MbnPeriodcTaskSms record, MbnPeriodcTaskSmsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByExampleWithBLOBs(MbnPeriodcTaskSms record, MbnPeriodcTaskSmsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByExampleWithoutBLOBs(MbnPeriodcTaskSms record, MbnPeriodcTaskSmsExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task_sms.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table mbn_periodc_task_sms
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private static class UpdateByExampleParms extends MbnPeriodcTaskSmsExample {
        private Object record;

        public UpdateByExampleParms(Object record, MbnPeriodcTaskSmsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}