package com.leadtone.mas.bizplug.calendar.dao;

import com.leadtone.mas.bizplug.calendar.bean.MbnPeriodcTask;
import com.leadtone.mas.bizplug.calendar.bean.MbnPeriodcTaskExample;
import com.leadtone.mas.bizplug.dao.BaseDao;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

@Component("smsMbnPeriodcTaskDAO")
public class MbnPeriodcTaskDAOImpl extends BaseDao implements MbnPeriodcTaskDAO {
   



    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public void insert(MbnPeriodcTask record) throws SQLException {
    	this.getSqlMapClientTemplate().insert("mbn_periodc_task.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByPrimaryKey(MbnPeriodcTask record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByPrimaryKeySelective(MbnPeriodcTask record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public List selectByExample(MbnPeriodcTaskExample example) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_periodc_task.abatorgenerated_selectByExample", example);
        return list;
    }
    
    public List selectTaskList(Map<String,Object> paraMap)throws SQLException{
    	List list =this.getSqlMapClientTemplate().queryForList("mbn_periodc_task.abatorgenerated_selectPeriodicTaskList",paraMap);
    	return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public MbnPeriodcTask selectByPrimaryKey(Long id) throws SQLException {
        MbnPeriodcTask key = new MbnPeriodcTask();
        key.setId(id);
        MbnPeriodcTask record = (MbnPeriodcTask) this.getSqlMapClientTemplate().queryForObject("mbn_periodc_task.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int deleteByExample(MbnPeriodcTaskExample example) throws SQLException {
        int rows = this.getSqlMapClientTemplate().delete("mbn_periodc_task.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        MbnPeriodcTask key = new MbnPeriodcTask();
        key.setId(id);
        int rows = this.getSqlMapClientTemplate().delete("mbn_periodc_task.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int countByExample(MbnPeriodcTaskExample example) throws SQLException {
        Integer count = (Integer)  this.getSqlMapClientTemplate().queryForObject("mbn_periodc_task.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByExampleSelective(MbnPeriodcTask record, MbnPeriodcTaskExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    public int updateByExample(MbnPeriodcTask record, MbnPeriodcTaskExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_periodc_task.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table mbn_periodc_task
     *
     * @abatorgenerated Fri Jan 25 10:45:02 CST 2013
     */
    private static class UpdateByExampleParms extends MbnPeriodcTaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, MbnPeriodcTaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}