package com.leadtone.mas.bizplug.calendar.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.leadtone.mas.bizplug.calendar.bean.MbnSmsDuanxinrili;
import com.leadtone.mas.bizplug.calendar.bean.MbnSmsDuanxinriliExample;
import com.leadtone.mas.bizplug.dao.BaseDao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Component;

@Component("smsMbnDuanxinriliDAO")
public class MbnSmsDuanxinriliDAOImpl extends BaseDao implements MbnSmsDuanxinriliDAO {

	
	

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public void insert(MbnSmsDuanxinrili record) throws SQLException {
    	this.getSqlMapClientTemplate().insert("mbn_sms_duanxinrili.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(MbnSmsDuanxinrili record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(MbnSmsDuanxinrili record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByPrimaryKeySelective(MbnSmsDuanxinrili record) throws SQLException {
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }
    /**
     * 待发箱查询分页列表
     */
    public List selectByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_sms_duanxinrili.selectCalendarListByPage", paraMap);
        return list;
    }
    /**
     * 待发箱查询总数
     */
    public int selectCountByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException {
        return  (Integer)this.getSqlMapClientTemplate().queryForObject("mbn_sms_duanxinrili.selectCountCalendarListByPage", paraMap);
    }
    /**
     * 已发箱查询分页列表
     * @param paraMap
     * @return
     * @throws SQLException
     */
    public List selectHadSendByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_sms_duanxinrili.selectHadSendCalendarListByPage", paraMap);
        return list;
    }
    /**
     * 已发箱查询总数
     * @param paraMap
     * @return
     * @throws SQLException
     */
    public int selectHadSendCountByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException {
        return  (Integer)this.getSqlMapClientTemplate().queryForObject("mbn_sms_duanxinrili.selectHadSendCountCalendarListByPage", paraMap);
    }
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public List selectByExampleWithoutBLOBs(MbnSmsDuanxinriliExample example) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_sms_duanxinrili.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public List selectByExampleWithBLOBs(MbnSmsDuanxinriliExample example) throws SQLException {
        List list = this.getSqlMapClientTemplate().queryForList("mbn_sms_duanxinrili.abatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public MbnSmsDuanxinrili selectByPrimaryKey(Long id) throws SQLException {
        MbnSmsDuanxinrili key = new MbnSmsDuanxinrili();
        key.setId(id);
        MbnSmsDuanxinrili record = (MbnSmsDuanxinrili) this.getSqlMapClientTemplate().queryForObject("mbn_sms_duanxinrili.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int deleteByExample(MbnSmsDuanxinriliExample example) throws SQLException {
        int rows = this.getSqlMapClientTemplate().delete("mbn_sms_duanxinrili.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        MbnSmsDuanxinrili key = new MbnSmsDuanxinrili();
        key.setId(id);
        int rows = this.getSqlMapClientTemplate().delete("mbn_sms_duanxinrili.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int countByExample(MbnSmsDuanxinriliExample example) throws SQLException {
        Integer count = (Integer)  this.getSqlMapClientTemplate().queryForObject("mbn_sms_duanxinrili.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByExampleSelective(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByExampleWithBLOBs(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    public int updateByExampleWithoutBLOBs(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.getSqlMapClientTemplate().update("mbn_sms_duanxinrili.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    private static class UpdateByExampleParms extends MbnSmsDuanxinriliExample {
        private Object record;

        public UpdateByExampleParms(Object record, MbnSmsDuanxinriliExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}