package com.leadtone.mas.bizplug.calendar.dao;

import com.leadtone.mas.bizplug.calendar.bean.MbnSmsDuanxinrili;
import com.leadtone.mas.bizplug.calendar.bean.MbnSmsDuanxinriliExample;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public interface MbnSmsDuanxinriliDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    void insert(MbnSmsDuanxinrili record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByPrimaryKeyWithoutBLOBs(MbnSmsDuanxinrili record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(MbnSmsDuanxinrili record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByPrimaryKeySelective(MbnSmsDuanxinrili record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    List selectByExampleWithoutBLOBs(MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    List selectByExampleWithBLOBs(MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    MbnSmsDuanxinrili selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int deleteByExample(MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int deleteByPrimaryKey(Long id) throws SQLException;
    
    public List selectByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException;

    public int selectCountByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException;
    
    public List selectHadSendByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException;

    public int selectHadSendCountByCreateWithoutExample(Map<String,Object> paraMap) throws SQLException;
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int countByExample(MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByExampleSelective(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByExampleWithBLOBs(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mbn_sms_duanxinrili
     *
     * @abatorgenerated Mon Jan 28 16:08:08 CST 2013
     */
    int updateByExampleWithoutBLOBs(MbnSmsDuanxinrili record, MbnSmsDuanxinriliExample example) throws SQLException;
}